
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Model from "./components/models/Model";
import LoginModel from "./components/models/LoginModel";
import SignupModel from "./components/models/SignupModel";
import AddPropertyModel from "./components/models/AddPropertyModel";
import SearchModel from "./components/models/SearchModel";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Djangobnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (<div className="p-4">This is a model content</div>)
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Navbar />
        <div className="pt-22">
          {children}
        </div>
        {/* <Model
          label="Sample Model"
          content={content}
          isOpen={true}
          
        /> */}
        <LoginModel />
        <SearchModel />
        <SignupModel />
        <AddPropertyModel />
       
      </body>
    </html>
  );
}
